stages:
  - validate
  - pre-tag
  - release
  - docker
  - tag
  - deploy
  - merge-request

variables:
  APK_CACHE_DIR: $CI_PROJECT_DIR/.cache/apk
  STAGING: staging # If use staging environment: staging / If don't use staging environment: production

cache:
  paths:
    - $CI_PROJECT_DIR/.cache/pip
    - $APK_CACHE_DIR

include:
  - remote: https://raw.githubusercontent.com/steplix/steplix-actions/main/aws/ecr-cloudformation/gitlab/base/pre.yml
  - remote: https://raw.githubusercontent.com/steplix/steplix-actions/main/aws/ecr-cloudformation/gitlab/base/mr.yml
  - remote: https://raw.githubusercontent.com/steplix/steplix-actions/main/aws/ecr-cloudformation/gitlab/base/testing.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "testing"

  - remote: https://raw.githubusercontent.com/steplix/steplix-actions/main/aws/ecr-cloudformation/gitlab/base/staging.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "master"

  - remote: https://raw.githubusercontent.com/steplix/steplix-actions/main/aws/ecr-cloudformation/gitlab/base/production.yml
    rules:
      - if: $CI_COMMIT_TAG

.verify:
  stage: validate
  image: node:18-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm ci --prefer-offline
  script:
    - npm test --if-present
    - npm run lint --if-present

verify:
  extends: .verify
  only:
    - develop

merge-request:
  extends: .merge-request
  stage: merge-request
  only:
    - develop
  variables:
    TARGET: testing
  needs:
    - verify

# Hot Fix
verify:hotfix:
  extends: .verify
  only:
    - /^hotfix/

mr-develop:hotfix:
  extends: .merge-request
  stage: merge-request
  needs:
    - verify:hotfix
  only:
    - /^hotfix/
  variables:
    TARGET: develop
    DELETE_SOURCE_BRANCH: 'true'
    TITLE: '#skip-pipeline Hot-fix'

mr-master:hotfix:
  extends: .merge-request
  stage: merge-request
  needs:
    - verify:hotfix
  only:
    - /^hotfix/
  variables:
    TARGET: master
    TITLE: Hot-fix
