name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  process-deploy:
    uses: steplix/steplix-actions/lambda/deploy-sam.yml
    with:
      environment: production
    secrets:
      variables: ${{ secrets.PROD_VARIABLES }}
      aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.PROD_AWS_REGION }}
