variables:
  VERSION: $CI_COMMIT_TAG

deploy:production:
  stage: deploy
  image: alpine
  allow_failure: false
  when: manual
  before_script:
    - apk add --cache-dir $APK_CACHE_DIR python3 py-pip
    - pip install awscli --break-system-packages
  script:
    - >
      aws cloudformation deploy
      --template-file ./cloudformation/cloudformation.yml
      --stack-name ${CI_PROJECT_NAME}-production
      --no-fail-on-empty-changeset
      --region ${AWS_DEFAULT_REGION}
      --parameter-overrides Environment=production ParameterSuffix=Production EnvAwsECRImage=${AWS_ECR_REPOSITORY}:${CI_COMMIT_TAG} ${AWS_CLOUDFORMATION_PARAMS_OVERRIDE}
  environment: production
