name: Develop check

on:
  push:
    branches:
      - develop

jobs:
  checking-process:
    uses: steplix/cicd-steplix/.github/workflows/lam-develop-check.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.TEST_AWS_REGION }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}