name: 1. Development validation

run-name: >
  Develop validate: ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - develop

jobs:
  develop:
    uses: steplix/cicd-steplix/.github/workflows/mob-react-native-develop-validate.yml@main
    with:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      PR_BRANCH: testing
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
