name: 2.b Hotfix validation

run-name: >
  Hotfix validation: ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - hotfix/**

jobs:
  hotfix:
    uses: steplix/cicd-steplix/.github/workflows/mob-react-native-hotfix.yml@main
    with:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      MAIN_BRANCH: master
      DEVELOP_BRANCH: develop
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
