name: 6. Production Android Deployment

run-name: >
  Production Android deployment: ${{ github.event.release.tag_name }}

on:
  registry_package:
    types:
      - published

jobs:
  production-android:
    if: contains(github.event.release.name, 'android')
    uses: steplix/cicd-steplix/.github/workflows/mob-react-native-production-deploy-android.yml@main
    with:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      ANDROID_KEYSTORE_NAME: ${{ vars.ANDROID_KEYSTORE_NAME }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ANDROID_SERVICE_ACCOUNT: ${{ secrets.ANDROID_SERVICE_ACCOUNT }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
