name: 7. Production iOS Deployment

run-name: >
  Production iOS deployment: ${{ github.event.release.tag_name }}

on:
  registry_package:
    types:
      - published

jobs:
  production-ios:
    if: contains(github.event.release.name, 'ios')
    uses: steplix/cicd-steplix/.github/workflows/mob-react-native-production-deploy-ios.yml@main
    with:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      PROJECT_PATH: ios/project.xcodeproj
      WORKSPACE_PATH: ios/project.xcworkspace
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      IOS_MOBILE_PROVISION_BASE64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
      IOS_P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
      IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}