name: Push in master branch
run-name: >
  ${{ github.event.pull_request.title }}

on:
  push:
    branches:
      - master


env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
  AWS_BUCKET: ${{ vars.PROD_AWS_BUCKET_ARTIFACT }}

jobs:

  master:
    uses: steplix/cicd-steplix/.github/workflows/web-s3-master-push.yml@feature/addStaticWebWorkflows
    with:
      NODE_VERSION: ${{ env.NODE_VERSION }}
      SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
      AWS_BUCKET: ${{ env.AWS_BUCKET }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      AWS_KEY_ID: ${{ secrets.TEST_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.TEST_AWS_REGION }}
