name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  process-deploy:
    uses: steplix/steplix-actions/.github/workflows/lam-deploy-sam.yml@latest
    with:
      environment: staging
      pr-branch: master
    secrets:
      variables: ${{ secrets.STAGE_VARIABLES }}
      aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.STAGE_AWS_REGION }}
