stages:
  - verify
  - deploy-test
  - deploy-stage
  - deploy-prod

.merge: &merge
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git remote set-url origin "https://${STEPLIX_GITLAB_ACCESS_USER}:${STEPLIX_GITLAB_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}"
  - git fetch --all
  - git checkout ${BRANCH}
  - git merge origin/${ORIGIN} -m "Pipeline - Auto merge ${BRANCH} with ${ORIGIN}"
  - git push -f origin ${BRANCH}

validate:sam:
  stage: verify
  image: public.ecr.aws/sam/build-nodejs16.x
  only:
    - develop
  script:
    - sam build
    - sam validate --config-env testing
  environment: testing

verify:
  stage: verify
  image: node:18-alpine
  only:
    - develop
  before_script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - cd src/
    - npm ci
  script:
    - npm test --if-present
    - npm run lint --if-present

deploy:test:
  stage: deploy-test
  image: public.ecr.aws/sam/build-nodejs16.x
  when: manual
  allow_failure: false
  only:
    - develop
  needs:
    - validate:sam
    - verify
  variables:
    BRANCH: testing
    ORIGIN: develop
  script:
    - *merge
    - sam build
    - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env testing --parameter-overrides Environment=testing
  environment: testing

deploy:stage:
  stage: deploy-stage
  image: public.ecr.aws/sam/build-nodejs16.x
  allow_failure: false
  only:
    - develop
  needs:
    - deploy:test
  variables:
    BRANCH: staging
    ORIGIN: testing
  script:
    - *merge
    - sam validate --config-env staging
    - sam build
    - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env staging --parameter-overrides Environment=staging "$TEMPLATE_VARS"
  environment: staging

deploy:prod:
  stage: deploy-prod
  image: public.ecr.aws/sam/build-nodejs16.x
  allow_failure: false
  only:
    - develop
  needs:
    - deploy:stage
  variables:
    BRANCH: master
    ORIGIN: staging
  script:
    - *merge
    - sam validate --config-env production
    - sam build
    - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env production --parameter-overrides Environment=production "$TEMPLATE_VARS"
  environment: production
