name: Hotfix validation

on:
  workflow_call:
    inputs:
      COMMIT_MESSAGE:
        type: string
        description: "Pass the head commit message {{ github.event.head_commit.message }}"
        required: true
      MAIN_BRANCH:
        type: string
        default: master
        description: Main branch
        required: false
      DEVELOP_BRANCH:
        type: string
        default: develop
        description: Development branch
        required: false
      NODE_VERSION:
        type: string
        default: '18'
        required: false
      DISABLE_CACHE:
        type: string
        default: 'false'
        description: Disable package.json cache
        required: false
      SLACK_CHANNEL:
        type: string
        description: Slack channel to send notifications
        required: false
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

env:
  MAIN_BRANCH: '${{ inputs.MAIN_BRANCH }}'
  DEVELOP_BRANCH: '${{ inputs.DEVELOP_BRANCH }}'
  COMMIT_MESSAGE: '${{ inputs.COMMIT_MESSAGE }}'
  NODE_VERSION: '${{ inputs.NODE_VERSION }}'
  DISABLE_CACHE: '${{ inputs.DISABLE_CACHE }}'
  SLACK_CHANNEL: '${{ inputs.SLACK_CHANNEL }}'

  # Secrets
  SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
    
      - uses: steplix/cicd-check-parameter@1.0.0
        id: args
        with:
          message: ${{ env.COMMIT_MESSAGE }}
          param-0: no-cache

      - name: Cache dependencies
        if: steps.args.outputs.param-0 != 'true' && env.DISABLE_CACHE != 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
    
      - run: npm run lint --if-present
      - run: npm run test --if-present

  create-pr:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      
      # Main pull request
      - name: Create ${{ env.MAIN_BRANCH }} Pull Request        
        uses: repo-sync/pull-request@v2
        id: main-pr
        with:
          source_branch: "${{ github.ref_name }}"
          destination_branch: "${{ env.MAIN_BRANCH }}"
          pr_title: "Hotfix deployment: ${{ github.ref }} #skip-staging-deploy"
          pr_body: |
            Automated PR
          github_token: ${{ env.GITHUB_TOKEN }}

      # Develop pull request
      - name: Create ${{ env.DEVELOP_BRANCH }} Pull Request
        uses: repo-sync/pull-request@v2
        id: develop-pr
        with:
          source_branch: "${{ github.ref_name }}"
          destination_branch: "${{ env.DEVELOP_BRANCH }}"
          pr_title: "Hotfix retro-merge: ${{ github.ref }} [skip ci]"
          pr_body: |
            Automated PR -- Merge as soon as possible, otherwise the staging deployment may be blocked
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Notify Slack
        uses: steplix/cicd-notify@1.0.0
        continue-on-error: true
        with:
          template: pr
          status: ${{ job.status }}
          channel: ${{ env.SLACK_CHANNEL }}
        env:
          PR_URL: ${{ steps.main-pr.outputs.pr_url }}
          PR_NUMBER: ${{ steps.main-pr.outputs.pr_number }}

  notify-failure:
    runs-on: ubuntu-latest
    needs:
      - validate
      - create-pr
    if: failure()
    continue-on-error: true
    steps:
      - name: Slack Notify
        uses: steplix/cicd-notify@1.0.0
        with:
          template: push
          status: failure
          channel: ${{ env.SLACK_CHANNEL }}
