name: Production Deployment

on:
  workflow_call:
    inputs:
      RELEASE_TAG:
        type: string
        required: true
      AWS_ECR_REPOSITORY:
        type: string
        description: "AWS ECR Repository name"
        required: true
      AWS_CF_STACK_NAME:
        type: string
        default: '${{ github.event.repository.name }}'
        description: "AWS cloud-formation stack name"
        required: false
      DISABLE_CACHE:
        type: string
        default: 'false'
        description: Disable docker cache
        required: false
      SLACK_CHANNEL:
        type: string
        description: Slack channel to send notifications
        required: false
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_CLOUDFORMATION_PARAMS_OVERRIDE:
        required: false

env:
  RELEASE_TAG: '${{ inputs.RELEASE_TAG }}'
  AWS_ECR_REPOSITORY: '${{ inputs.AWS_ECR_REPOSITORY }}'
  AWS_CF_STACK_NAME: '${{ inputs.AWS_CF_STACK_NAME }}'
  DISABLE_CACHE: '${{ inputs.DISABLE_CACHE }}'
  SLACK_CHANNEL: '${{ inputs.SLACK_CHANNEL }}'

  # Secrets
  SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  AWS_REGION: '${{ secrets.AWS_REGION }}'
  AWS_CLOUDFORMATION_PARAMS_OVERRIDE: '${{ secrets.AWS_CLOUDFORMATION_PARAMS_OVERRIDE }}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: steplix/cicd-steplix-deploy-ecr-and-cloudformation@v1
        with:
          ENVIRONMENT: production
          AWS_ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
          AWS_CF_STACK_NAME: ${{ env.AWS_CF_STACK_NAME }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_CLOUDFORMATION_PARAMS_OVERRIDE: ${{ env.AWS_CLOUDFORMATION_PARAMS_OVERRIDE }}
          TAG: ${{ env.RELEASE_TAG }}
          DISABLE_CACHE: ${{ env.DISABLE_CACHE }}

  notify:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: success() || failure()
    continue-on-error: true
    steps:
      - name: Slack Notify
        uses: steplix/cicd-notify@1.0.0
        with:
          template: push
          status: ${{ needs.deploy.result }}
          channel: ${{ env.SLACK_CHANNEL }}
