name: >
  Validate node applications by running tests. 
  Caching dependencies based on package-lock.json

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        default: '20.16.0'
        required: false
      ENABLE_CACHE:
        type: string
        default: 'true'
        description: Enable package.json cache
        required: false
      CACHE_DEPENDENCY_PATH:
        type: string
        default: '.'
        description: Path package-lock.json cache
        required: false

env:
  NODE_VERSION: '${{ inputs.NODE_VERSION }}'
  ENABLE_CACHE: '${{ inputs.ENABLE_CACHE }}'
  CACHE_DEPENDENCY_PATH: '${{ inputs.CACHE_DEPENDENCY_PATH }}'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.ENABLE_CACHE == 'true' && 'npm' || '' }}
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}/package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ${{ env.CACHE_DEPENDENCY_PATH }}
      - name: Run tests
        run: npm run test --if-present
        working-directory: ${{ env.CACHE_DEPENDENCY_PATH }}
